//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluescreenSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Windows10BluescreenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Windows10BluescreenResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluescreenSimulator.Properties.Windows10BluescreenResources", typeof(Windows10BluescreenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 :( 的本地化字符串。
        /// </summary>
        public static string Emoticon {
            get {
                return ResourceManager.GetString("Emoticon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的设备遇到问题，需要重启。 的本地化字符串。
        /// </summary>
        public static string MainText1 {
            get {
                return ResourceManager.GetString("MainText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们只收集某些错误信息，然后为你重新启动。 的本地化字符串。
        /// </summary>
        public static string MainText2 {
            get {
                return ResourceManager.GetString("MainText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有关此问题的详细信息和可能的解决方法，请访问https://www.windows.com/stopcode 的本地化字符串。
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止代码：DRIVER_IRQL_NOT_LESS_OR_EQUAL 的本地化字符串。
        /// </summary>
        public static string StopCode {
            get {
                return ResourceManager.GetString("StopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果致电支持人员，请向他们提供以下信息： 的本地化字符串。
        /// </summary>
        public static string SupportPerson {
            get {
                return ResourceManager.GetString("SupportPerson", resourceCulture);
            }
        }
    }
}
